name: Fail-fast matrix
on: push
jobs:
  runs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false   #マトリックスのフェイルファストを無効化する
      matrix:
        time: [10,20,30] #ジョブ毎に異なる時間をスリープさせる
    steps:
      - run: sleep "${SLEEP_TIME}" && exit 1
        env:
          SLEEP_TIME: ${{ matrix.time }}